{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\keras\\src\\layers\\convolutional\\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.\n",
      "  super().__init__(activity_regularizer=activity_regularizer, **kwargs)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1m301/301\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m1s\u001b[0m 5ms/step\n",
      "\u001b[1m129/129\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m1s\u001b[0m 4ms/step\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2024-05-27 01:58:26,942] A new study created in memory with name: no-name-5b4aada8-ac76-428a-8ae0-dab13cfe5238\n",
      "[I 2024-05-27 03:53:59,313] Trial 0 finished with value: 0.5908266466196238 and parameters: {'n_estimators': 59, 'max_depth': 5, 'learning_rate': 0.0011490394246152652, 'subsample': 0.6926982467930112, 'colsample_bytree': 0.5074292779558145}. Best is trial 0 with value: 0.5908266466196238.\n",
      "[I 2024-05-27 16:24:22,039] Trial 1 finished with value: 0.6322152827803349 and parameters: {'n_estimators': 78, 'max_depth': 8, 'learning_rate': 0.002500250850244193, 'subsample': 0.9167852584671607, 'colsample_bytree': 0.6414209231291539}. Best is trial 1 with value: 0.6322152827803349.\n",
      "[W 2024-05-27 16:53:48,618] Trial 2 failed with parameters: {'n_estimators': 77, 'max_depth': 16, 'learning_rate': 0.00016593943473621855, 'subsample': 0.9404422683493163, 'colsample_bytree': 0.8340373187608296} because of the following error: ValueError('\\nAll the 10 fits failed.\\nIt is very likely that your model is misconfigured.\\nYou can try to debug the error by setting error_score=\\'raise\\'.\\n\\nBelow are more details about the failures:\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\model_selection\\\\_validation.py\", line 895, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 669, in fit\\n    return super().fit(X, y_encoded, sample_weight)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\base.py\", line 1474, in wrapper\\n    return fit_method(estimator, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 216, in fit\\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 67, in __call__\\n    return super().__call__(iterable_with_config)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1863, in __call__\\n    return output if self.return_generator else list(output)\\n                                                ^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1792, in _get_sequential_output\\n    res = func(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 129, in __call__\\n    return self.function(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_base.py\", line 36, in _fit_single_estimator\\n    estimator.fit(X, y)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\sklearn.py\", line 1519, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\training.py\", line 181, in train\\n    bst.update(dtrain, i, obj)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 2050, in update\\n    _check_call(\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 282, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [16:26:55] C:\\\\buildkite-agent\\\\builds\\\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\\\xgboost\\\\xgboost-ci-windows\\\\src\\\\common\\\\io.h:232: bad_malloc: Failed to allocate 5884167968 bytes.\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\model_selection\\\\_validation.py\", line 895, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 669, in fit\\n    return super().fit(X, y_encoded, sample_weight)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\base.py\", line 1474, in wrapper\\n    return fit_method(estimator, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 216, in fit\\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 67, in __call__\\n    return super().__call__(iterable_with_config)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1863, in __call__\\n    return output if self.return_generator else list(output)\\n                                                ^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1792, in _get_sequential_output\\n    res = func(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 129, in __call__\\n    return self.function(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_base.py\", line 36, in _fit_single_estimator\\n    estimator.fit(X, y)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\sklearn.py\", line 1519, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\training.py\", line 181, in train\\n    bst.update(dtrain, i, obj)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 2050, in update\\n    _check_call(\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 282, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [16:29:31] C:\\\\buildkite-agent\\\\builds\\\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\\\xgboost\\\\xgboost-ci-windows\\\\src\\\\common\\\\io.h:232: bad_malloc: Failed to allocate 6133974000 bytes.\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\model_selection\\\\_validation.py\", line 895, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 669, in fit\\n    return super().fit(X, y_encoded, sample_weight)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\base.py\", line 1474, in wrapper\\n    return fit_method(estimator, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 216, in fit\\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 67, in __call__\\n    return super().__call__(iterable_with_config)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1863, in __call__\\n    return output if self.return_generator else list(output)\\n                                                ^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1792, in _get_sequential_output\\n    res = func(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 129, in __call__\\n    return self.function(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_base.py\", line 36, in _fit_single_estimator\\n    estimator.fit(X, y)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\sklearn.py\", line 1519, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\training.py\", line 181, in train\\n    bst.update(dtrain, i, obj)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 2050, in update\\n    _check_call(\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 282, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [16:32:09] C:\\\\buildkite-agent\\\\builds\\\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\\\xgboost\\\\xgboost-ci-windows\\\\src\\\\common\\\\io.h:232: bad_malloc: Failed to allocate 6169047456 bytes.\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\model_selection\\\\_validation.py\", line 895, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 669, in fit\\n    return super().fit(X, y_encoded, sample_weight)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\base.py\", line 1474, in wrapper\\n    return fit_method(estimator, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 216, in fit\\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 67, in __call__\\n    return super().__call__(iterable_with_config)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1863, in __call__\\n    return output if self.return_generator else list(output)\\n                                                ^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1792, in _get_sequential_output\\n    res = func(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 129, in __call__\\n    return self.function(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_base.py\", line 36, in _fit_single_estimator\\n    estimator.fit(X, y)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\sklearn.py\", line 1519, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\training.py\", line 181, in train\\n    bst.update(dtrain, i, obj)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 2050, in update\\n    _check_call(\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 282, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [16:34:42] C:\\\\buildkite-agent\\\\builds\\\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\\\xgboost\\\\xgboost-ci-windows\\\\src\\\\common\\\\io.h:232: bad_malloc: Failed to allocate 6652229584 bytes.\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\model_selection\\\\_validation.py\", line 895, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 669, in fit\\n    return super().fit(X, y_encoded, sample_weight)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\base.py\", line 1474, in wrapper\\n    return fit_method(estimator, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 216, in fit\\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 67, in __call__\\n    return super().__call__(iterable_with_config)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1863, in __call__\\n    return output if self.return_generator else list(output)\\n                                                ^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1792, in _get_sequential_output\\n    res = func(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 129, in __call__\\n    return self.function(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_base.py\", line 36, in _fit_single_estimator\\n    estimator.fit(X, y)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\sklearn.py\", line 1519, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\training.py\", line 181, in train\\n    bst.update(dtrain, i, obj)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 2050, in update\\n    _check_call(\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 282, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [16:37:10] C:\\\\buildkite-agent\\\\builds\\\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\\\xgboost\\\\xgboost-ci-windows\\\\src\\\\common\\\\io.h:232: bad_malloc: Failed to allocate 5852398160 bytes.\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\model_selection\\\\_validation.py\", line 895, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 669, in fit\\n    return super().fit(X, y_encoded, sample_weight)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\base.py\", line 1474, in wrapper\\n    return fit_method(estimator, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 216, in fit\\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 67, in __call__\\n    return super().__call__(iterable_with_config)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1863, in __call__\\n    return output if self.return_generator else list(output)\\n                                                ^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1792, in _get_sequential_output\\n    res = func(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 129, in __call__\\n    return self.function(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_base.py\", line 36, in _fit_single_estimator\\n    estimator.fit(X, y)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\sklearn.py\", line 1519, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\training.py\", line 181, in train\\n    bst.update(dtrain, i, obj)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 2050, in update\\n    _check_call(\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 282, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [16:39:37] C:\\\\buildkite-agent\\\\builds\\\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\\\xgboost\\\\xgboost-ci-windows\\\\src\\\\common\\\\io.h:232: bad_malloc: Failed to allocate 5733040016 bytes.\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\model_selection\\\\_validation.py\", line 895, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 669, in fit\\n    return super().fit(X, y_encoded, sample_weight)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\base.py\", line 1474, in wrapper\\n    return fit_method(estimator, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 216, in fit\\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 67, in __call__\\n    return super().__call__(iterable_with_config)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1863, in __call__\\n    return output if self.return_generator else list(output)\\n                                                ^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1792, in _get_sequential_output\\n    res = func(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 129, in __call__\\n    return self.function(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_base.py\", line 36, in _fit_single_estimator\\n    estimator.fit(X, y)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\sklearn.py\", line 1519, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\training.py\", line 181, in train\\n    bst.update(dtrain, i, obj)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 2050, in update\\n    _check_call(\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 282, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [16:42:04] C:\\\\buildkite-agent\\\\builds\\\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\\\xgboost\\\\xgboost-ci-windows\\\\src\\\\common\\\\io.h:232: bad_malloc: Failed to allocate 5980455040 bytes.\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\model_selection\\\\_validation.py\", line 895, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 669, in fit\\n    return super().fit(X, y_encoded, sample_weight)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\base.py\", line 1474, in wrapper\\n    return fit_method(estimator, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 216, in fit\\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 67, in __call__\\n    return super().__call__(iterable_with_config)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1863, in __call__\\n    return output if self.return_generator else list(output)\\n                                                ^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1792, in _get_sequential_output\\n    res = func(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 129, in __call__\\n    return self.function(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_base.py\", line 36, in _fit_single_estimator\\n    estimator.fit(X, y)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\sklearn.py\", line 1519, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\training.py\", line 181, in train\\n    bst.update(dtrain, i, obj)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 2050, in update\\n    _check_call(\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 282, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [16:44:28] C:\\\\buildkite-agent\\\\builds\\\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\\\xgboost\\\\xgboost-ci-windows\\\\src\\\\common\\\\io.h:232: bad_malloc: Failed to allocate 5697385776 bytes.\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\model_selection\\\\_validation.py\", line 895, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 669, in fit\\n    return super().fit(X, y_encoded, sample_weight)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\base.py\", line 1474, in wrapper\\n    return fit_method(estimator, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 216, in fit\\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 67, in __call__\\n    return super().__call__(iterable_with_config)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1863, in __call__\\n    return output if self.return_generator else list(output)\\n                                                ^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1792, in _get_sequential_output\\n    res = func(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 129, in __call__\\n    return self.function(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_base.py\", line 36, in _fit_single_estimator\\n    estimator.fit(X, y)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\sklearn.py\", line 1519, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\training.py\", line 181, in train\\n    bst.update(dtrain, i, obj)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 2050, in update\\n    _check_call(\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 282, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [16:47:08] C:\\\\buildkite-agent\\\\builds\\\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\\\xgboost\\\\xgboost-ci-windows\\\\src\\\\common\\\\io.h:232: bad_malloc: Failed to allocate 5992455504 bytes.\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\model_selection\\\\_validation.py\", line 895, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 669, in fit\\n    return super().fit(X, y_encoded, sample_weight)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\base.py\", line 1474, in wrapper\\n    return fit_method(estimator, *args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_stacking.py\", line 216, in fit\\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 67, in __call__\\n    return super().__call__(iterable_with_config)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1863, in __call__\\n    return output if self.return_generator else list(output)\\n                                                ^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\joblib\\\\parallel.py\", line 1792, in _get_sequential_output\\n    res = func(*args, **kwargs)\\n          ^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\utils\\\\parallel.py\", line 129, in __call__\\n    return self.function(*args, **kwargs)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\sklearn\\\\ensemble\\\\_base.py\", line 36, in _fit_single_estimator\\n    estimator.fit(X, y)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\sklearn.py\", line 1519, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 730, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\training.py\", line 181, in train\\n    bst.update(dtrain, i, obj)\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 2050, in update\\n    _check_call(\\n  File \"C:\\\\Users\\\\UC\\\\AppData\\\\Roaming\\\\Python\\\\Python311\\\\site-packages\\\\xgboost\\\\core.py\", line 282, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [16:53:47] C:\\\\buildkite-agent\\\\builds\\\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\\\xgboost\\\\xgboost-ci-windows\\\\src\\\\common\\\\io.h:232: bad_malloc: Failed to allocate 5514815664 bytes.\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\optuna\\study\\_optimize.py\", line 196, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Local\\Temp\\ipykernel_23004\\2668248498.py\", line 124, in objective\n",
      "    scores = cross_val_score(ensemble_clf, x_train_combined, y_train, cv=skf, scoring='roc_auc')\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\_param_validation.py\", line 213, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 719, in cross_val_score\n",
      "    cv_results = cross_validate(\n",
      "                 ^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\_param_validation.py\", line 213, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 450, in cross_validate\n",
      "    _warn_or_raise_about_fit_failures(results, error_score)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 536, in _warn_or_raise_about_fit_failures\n",
      "    raise ValueError(all_fits_failed_message)\n",
      "ValueError: \n",
      "All the 10 fits failed.\n",
      "It is very likely that your model is misconfigured.\n",
      "You can try to debug the error by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n",
      "    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "                                                ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n",
      "    estimator.fit(X, y)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n",
      "    bst.update(dtrain, i, obj)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n",
      "    _check_call(\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [16:26:55] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5884167968 bytes.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n",
      "    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "                                                ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n",
      "    estimator.fit(X, y)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n",
      "    bst.update(dtrain, i, obj)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n",
      "    _check_call(\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [16:29:31] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 6133974000 bytes.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n",
      "    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "                                                ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n",
      "    estimator.fit(X, y)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n",
      "    bst.update(dtrain, i, obj)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n",
      "    _check_call(\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [16:32:09] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 6169047456 bytes.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n",
      "    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "                                                ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n",
      "    estimator.fit(X, y)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n",
      "    bst.update(dtrain, i, obj)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n",
      "    _check_call(\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [16:34:42] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 6652229584 bytes.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n",
      "    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "                                                ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n",
      "    estimator.fit(X, y)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n",
      "    bst.update(dtrain, i, obj)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n",
      "    _check_call(\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [16:37:10] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5852398160 bytes.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n",
      "    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "                                                ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n",
      "    estimator.fit(X, y)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n",
      "    bst.update(dtrain, i, obj)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n",
      "    _check_call(\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [16:39:37] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5733040016 bytes.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n",
      "    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "                                                ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n",
      "    estimator.fit(X, y)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n",
      "    bst.update(dtrain, i, obj)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n",
      "    _check_call(\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [16:42:04] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5980455040 bytes.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n",
      "    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "                                                ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n",
      "    estimator.fit(X, y)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n",
      "    bst.update(dtrain, i, obj)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n",
      "    _check_call(\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [16:44:28] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5697385776 bytes.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n",
      "    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "                                                ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n",
      "    estimator.fit(X, y)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n",
      "    bst.update(dtrain, i, obj)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n",
      "    _check_call(\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [16:47:08] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5992455504 bytes.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n",
      "    return super().fit(X, y_encoded, sample_weight)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n",
      "    return fit_method(estimator, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n",
      "    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n",
      "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n",
      "    return super().__call__(iterable_with_config)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n",
      "    return output if self.return_generator else list(output)\n",
      "                                                ^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n",
      "    res = func(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n",
      "    return self.function(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n",
      "    estimator.fit(X, y)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n",
      "    bst.update(dtrain, i, obj)\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n",
      "    _check_call(\n",
      "  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [16:53:47] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5514815664 bytes.\n",
      "\n",
      "[W 2024-05-27 16:53:48,742] Trial 2 failed with value None.\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "\nAll the 10 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:26:55] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5884167968 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:29:31] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 6133974000 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:32:09] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 6169047456 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:34:42] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 6652229584 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:37:10] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5852398160 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:39:37] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5733040016 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:42:04] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5980455040 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:44:28] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5697385776 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:47:08] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5992455504 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:53:47] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5514815664 bytes.\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[7], line 130\u001b[0m\n\u001b[0;32m    128\u001b[0m \u001b[38;5;66;03m# Optimize hyperparameters\u001b[39;00m\n\u001b[0;32m    129\u001b[0m study \u001b[38;5;241m=\u001b[39m optuna\u001b[38;5;241m.\u001b[39mcreate_study(direction\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mmaximize\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m--> 130\u001b[0m \u001b[43mstudy\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moptimize\u001b[49m\u001b[43m(\u001b[49m\u001b[43mobjective\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mn_trials\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m    132\u001b[0m \u001b[38;5;66;03m# Get the best hyperparameters\u001b[39;00m\n\u001b[0;32m    133\u001b[0m best_params \u001b[38;5;241m=\u001b[39m study\u001b[38;5;241m.\u001b[39mbest_params\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python311\\site-packages\\optuna\\study\\study.py:451\u001b[0m, in \u001b[0;36mStudy.optimize\u001b[1;34m(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)\u001b[0m\n\u001b[0;32m    348\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21moptimize\u001b[39m(\n\u001b[0;32m    349\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[0;32m    350\u001b[0m     func: ObjectiveFuncType,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    357\u001b[0m     show_progress_bar: \u001b[38;5;28mbool\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[0;32m    358\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    359\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Optimize an objective function.\u001b[39;00m\n\u001b[0;32m    360\u001b[0m \n\u001b[0;32m    361\u001b[0m \u001b[38;5;124;03m    Optimization is done by choosing a suitable set of hyperparameter values from a given\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    449\u001b[0m \u001b[38;5;124;03m            If nested invocation of this method occurs.\u001b[39;00m\n\u001b[0;32m    450\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m--> 451\u001b[0m     \u001b[43m_optimize\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    452\u001b[0m \u001b[43m        \u001b[49m\u001b[43mstudy\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m    453\u001b[0m \u001b[43m        \u001b[49m\u001b[43mfunc\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    454\u001b[0m \u001b[43m        \u001b[49m\u001b[43mn_trials\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn_trials\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    455\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    456\u001b[0m \u001b[43m        \u001b[49m\u001b[43mn_jobs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn_jobs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    457\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcatch\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mtuple\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43misinstance\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mIterable\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43m(\u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m,\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    458\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcallbacks\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    459\u001b[0m \u001b[43m        \u001b[49m\u001b[43mgc_after_trial\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mgc_after_trial\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    460\u001b[0m \u001b[43m        \u001b[49m\u001b[43mshow_progress_bar\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mshow_progress_bar\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    461\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python311\\site-packages\\optuna\\study\\_optimize.py:62\u001b[0m, in \u001b[0;36m_optimize\u001b[1;34m(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)\u001b[0m\n\u001b[0;32m     60\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m     61\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m n_jobs \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m1\u001b[39m:\n\u001b[1;32m---> 62\u001b[0m         \u001b[43m_optimize_sequential\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m     63\u001b[0m \u001b[43m            \u001b[49m\u001b[43mstudy\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     64\u001b[0m \u001b[43m            \u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     65\u001b[0m \u001b[43m            \u001b[49m\u001b[43mn_trials\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     66\u001b[0m \u001b[43m            \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     67\u001b[0m \u001b[43m            \u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     68\u001b[0m \u001b[43m            \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     69\u001b[0m \u001b[43m            \u001b[49m\u001b[43mgc_after_trial\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     70\u001b[0m \u001b[43m            \u001b[49m\u001b[43mreseed_sampler_rng\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m     71\u001b[0m \u001b[43m            \u001b[49m\u001b[43mtime_start\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m     72\u001b[0m \u001b[43m            \u001b[49m\u001b[43mprogress_bar\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mprogress_bar\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     73\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     74\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m     75\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m n_jobs \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m:\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python311\\site-packages\\optuna\\study\\_optimize.py:159\u001b[0m, in \u001b[0;36m_optimize_sequential\u001b[1;34m(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)\u001b[0m\n\u001b[0;32m    156\u001b[0m         \u001b[38;5;28;01mbreak\u001b[39;00m\n\u001b[0;32m    158\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 159\u001b[0m     frozen_trial \u001b[38;5;241m=\u001b[39m \u001b[43m_run_trial\u001b[49m\u001b[43m(\u001b[49m\u001b[43mstudy\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    160\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m    161\u001b[0m     \u001b[38;5;66;03m# The following line mitigates memory problems that can be occurred in some\u001b[39;00m\n\u001b[0;32m    162\u001b[0m     \u001b[38;5;66;03m# environments (e.g., services that use computing containers such as GitHub Actions).\u001b[39;00m\n\u001b[0;32m    163\u001b[0m     \u001b[38;5;66;03m# Please refer to the following PR for further details:\u001b[39;00m\n\u001b[0;32m    164\u001b[0m     \u001b[38;5;66;03m# https://github.com/optuna/optuna/pull/325.\u001b[39;00m\n\u001b[0;32m    165\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m gc_after_trial:\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python311\\site-packages\\optuna\\study\\_optimize.py:247\u001b[0m, in \u001b[0;36m_run_trial\u001b[1;34m(study, func, catch)\u001b[0m\n\u001b[0;32m    240\u001b[0m         \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mShould not reach.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    242\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m (\n\u001b[0;32m    243\u001b[0m     frozen_trial\u001b[38;5;241m.\u001b[39mstate \u001b[38;5;241m==\u001b[39m TrialState\u001b[38;5;241m.\u001b[39mFAIL\n\u001b[0;32m    244\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m func_err \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m    245\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(func_err, catch)\n\u001b[0;32m    246\u001b[0m ):\n\u001b[1;32m--> 247\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m func_err\n\u001b[0;32m    248\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m frozen_trial\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python311\\site-packages\\optuna\\study\\_optimize.py:196\u001b[0m, in \u001b[0;36m_run_trial\u001b[1;34m(study, func, catch)\u001b[0m\n\u001b[0;32m    194\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m get_heartbeat_thread(trial\u001b[38;5;241m.\u001b[39m_trial_id, study\u001b[38;5;241m.\u001b[39m_storage):\n\u001b[0;32m    195\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 196\u001b[0m         value_or_values \u001b[38;5;241m=\u001b[39m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrial\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    197\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m exceptions\u001b[38;5;241m.\u001b[39mTrialPruned \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    198\u001b[0m         \u001b[38;5;66;03m# TODO(mamu): Handle multi-objective cases.\u001b[39;00m\n\u001b[0;32m    199\u001b[0m         state \u001b[38;5;241m=\u001b[39m TrialState\u001b[38;5;241m.\u001b[39mPRUNED\n",
      "Cell \u001b[1;32mIn[7], line 124\u001b[0m, in \u001b[0;36mobjective\u001b[1;34m(trial)\u001b[0m\n\u001b[0;32m    122\u001b[0m \u001b[38;5;66;03m# Cross-validation\u001b[39;00m\n\u001b[0;32m    123\u001b[0m skf \u001b[38;5;241m=\u001b[39m StratifiedKFold(n_splits\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m10\u001b[39m, shuffle\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m, random_state\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m42\u001b[39m)\n\u001b[1;32m--> 124\u001b[0m scores \u001b[38;5;241m=\u001b[39m \u001b[43mcross_val_score\u001b[49m\u001b[43m(\u001b[49m\u001b[43mensemble_clf\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mx_train_combined\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcv\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mskf\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mscoring\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mroc_auc\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m    126\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m np\u001b[38;5;241m.\u001b[39mmean(scores)\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\_param_validation.py:213\u001b[0m, in \u001b[0;36mvalidate_params.<locals>.decorator.<locals>.wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    207\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m    208\u001b[0m     \u001b[38;5;28;01mwith\u001b[39;00m config_context(\n\u001b[0;32m    209\u001b[0m         skip_parameter_validation\u001b[38;5;241m=\u001b[39m(\n\u001b[0;32m    210\u001b[0m             prefer_skip_nested_validation \u001b[38;5;129;01mor\u001b[39;00m global_skip_validation\n\u001b[0;32m    211\u001b[0m         )\n\u001b[0;32m    212\u001b[0m     ):\n\u001b[1;32m--> 213\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    214\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m InvalidParameterError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    215\u001b[0m     \u001b[38;5;66;03m# When the function is just a wrapper around an estimator, we allow\u001b[39;00m\n\u001b[0;32m    216\u001b[0m     \u001b[38;5;66;03m# the function to delegate validation to the estimator, but we replace\u001b[39;00m\n\u001b[0;32m    217\u001b[0m     \u001b[38;5;66;03m# the name of the estimator by the name of the function in the error\u001b[39;00m\n\u001b[0;32m    218\u001b[0m     \u001b[38;5;66;03m# message to avoid confusion.\u001b[39;00m\n\u001b[0;32m    219\u001b[0m     msg \u001b[38;5;241m=\u001b[39m re\u001b[38;5;241m.\u001b[39msub(\n\u001b[0;32m    220\u001b[0m         \u001b[38;5;124mr\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mparameter of \u001b[39m\u001b[38;5;124m\\\u001b[39m\u001b[38;5;124mw+ must be\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    221\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mparameter of \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfunc\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__qualname__\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m must be\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    222\u001b[0m         \u001b[38;5;28mstr\u001b[39m(e),\n\u001b[0;32m    223\u001b[0m     )\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py:719\u001b[0m, in \u001b[0;36mcross_val_score\u001b[1;34m(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, params, pre_dispatch, error_score)\u001b[0m\n\u001b[0;32m    716\u001b[0m \u001b[38;5;66;03m# To ensure multimetric format is not supported\u001b[39;00m\n\u001b[0;32m    717\u001b[0m scorer \u001b[38;5;241m=\u001b[39m check_scoring(estimator, scoring\u001b[38;5;241m=\u001b[39mscoring)\n\u001b[1;32m--> 719\u001b[0m cv_results \u001b[38;5;241m=\u001b[39m \u001b[43mcross_validate\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    720\u001b[0m \u001b[43m    \u001b[49m\u001b[43mestimator\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mestimator\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    721\u001b[0m \u001b[43m    \u001b[49m\u001b[43mX\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mX\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    722\u001b[0m \u001b[43m    \u001b[49m\u001b[43my\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43my\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    723\u001b[0m \u001b[43m    \u001b[49m\u001b[43mgroups\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mgroups\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    724\u001b[0m \u001b[43m    \u001b[49m\u001b[43mscoring\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m{\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mscore\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mscorer\u001b[49m\u001b[43m}\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    725\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcv\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcv\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    726\u001b[0m \u001b[43m    \u001b[49m\u001b[43mn_jobs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn_jobs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    727\u001b[0m \u001b[43m    \u001b[49m\u001b[43mverbose\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mverbose\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    728\u001b[0m \u001b[43m    \u001b[49m\u001b[43mfit_params\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfit_params\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    729\u001b[0m \u001b[43m    \u001b[49m\u001b[43mparams\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mparams\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    730\u001b[0m \u001b[43m    \u001b[49m\u001b[43mpre_dispatch\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mpre_dispatch\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    731\u001b[0m \u001b[43m    \u001b[49m\u001b[43merror_score\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43merror_score\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    732\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    733\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m cv_results[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtest_score\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\_param_validation.py:213\u001b[0m, in \u001b[0;36mvalidate_params.<locals>.decorator.<locals>.wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    207\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m    208\u001b[0m     \u001b[38;5;28;01mwith\u001b[39;00m config_context(\n\u001b[0;32m    209\u001b[0m         skip_parameter_validation\u001b[38;5;241m=\u001b[39m(\n\u001b[0;32m    210\u001b[0m             prefer_skip_nested_validation \u001b[38;5;129;01mor\u001b[39;00m global_skip_validation\n\u001b[0;32m    211\u001b[0m         )\n\u001b[0;32m    212\u001b[0m     ):\n\u001b[1;32m--> 213\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    214\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m InvalidParameterError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    215\u001b[0m     \u001b[38;5;66;03m# When the function is just a wrapper around an estimator, we allow\u001b[39;00m\n\u001b[0;32m    216\u001b[0m     \u001b[38;5;66;03m# the function to delegate validation to the estimator, but we replace\u001b[39;00m\n\u001b[0;32m    217\u001b[0m     \u001b[38;5;66;03m# the name of the estimator by the name of the function in the error\u001b[39;00m\n\u001b[0;32m    218\u001b[0m     \u001b[38;5;66;03m# message to avoid confusion.\u001b[39;00m\n\u001b[0;32m    219\u001b[0m     msg \u001b[38;5;241m=\u001b[39m re\u001b[38;5;241m.\u001b[39msub(\n\u001b[0;32m    220\u001b[0m         \u001b[38;5;124mr\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mparameter of \u001b[39m\u001b[38;5;124m\\\u001b[39m\u001b[38;5;124mw+ must be\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    221\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mparameter of \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfunc\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__qualname__\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m must be\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    222\u001b[0m         \u001b[38;5;28mstr\u001b[39m(e),\n\u001b[0;32m    223\u001b[0m     )\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py:450\u001b[0m, in \u001b[0;36mcross_validate\u001b[1;34m(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, params, pre_dispatch, return_train_score, return_estimator, return_indices, error_score)\u001b[0m\n\u001b[0;32m    429\u001b[0m parallel \u001b[38;5;241m=\u001b[39m Parallel(n_jobs\u001b[38;5;241m=\u001b[39mn_jobs, verbose\u001b[38;5;241m=\u001b[39mverbose, pre_dispatch\u001b[38;5;241m=\u001b[39mpre_dispatch)\n\u001b[0;32m    430\u001b[0m results \u001b[38;5;241m=\u001b[39m parallel(\n\u001b[0;32m    431\u001b[0m     delayed(_fit_and_score)(\n\u001b[0;32m    432\u001b[0m         clone(estimator),\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    447\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m train, test \u001b[38;5;129;01min\u001b[39;00m indices\n\u001b[0;32m    448\u001b[0m )\n\u001b[1;32m--> 450\u001b[0m \u001b[43m_warn_or_raise_about_fit_failures\u001b[49m\u001b[43m(\u001b[49m\u001b[43mresults\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43merror_score\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    452\u001b[0m \u001b[38;5;66;03m# For callable scoring, the return type is only know after calling. If the\u001b[39;00m\n\u001b[0;32m    453\u001b[0m \u001b[38;5;66;03m# return type is a dictionary, the error scores can now be inserted with\u001b[39;00m\n\u001b[0;32m    454\u001b[0m \u001b[38;5;66;03m# the correct key.\u001b[39;00m\n\u001b[0;32m    455\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mcallable\u001b[39m(scoring):\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py:536\u001b[0m, in \u001b[0;36m_warn_or_raise_about_fit_failures\u001b[1;34m(results, error_score)\u001b[0m\n\u001b[0;32m    529\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m num_failed_fits \u001b[38;5;241m==\u001b[39m num_fits:\n\u001b[0;32m    530\u001b[0m     all_fits_failed_message \u001b[38;5;241m=\u001b[39m (\n\u001b[0;32m    531\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124mAll the \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m fits failed.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    532\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIt is very likely that your model is misconfigured.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    533\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mYou can try to debug the error by setting error_score=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mraise\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    534\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBelow are more details about the failures:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mfit_errors_summary\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    535\u001b[0m     )\n\u001b[1;32m--> 536\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(all_fits_failed_message)\n\u001b[0;32m    538\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    539\u001b[0m     some_fits_failed_message \u001b[38;5;241m=\u001b[39m (\n\u001b[0;32m    540\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mnum_failed_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m fits failed out of a total of \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    541\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mThe score on these train-test partitions for these parameters\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    545\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBelow are more details about the failures:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mfit_errors_summary\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    546\u001b[0m     )\n",
      "\u001b[1;31mValueError\u001b[0m: \nAll the 10 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:26:55] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5884167968 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:29:31] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 6133974000 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:32:09] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 6169047456 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:34:42] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 6652229584 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:37:10] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5852398160 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:39:37] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5733040016 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:42:04] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5980455040 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:44:28] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5697385776 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:47:08] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5992455504 bytes.\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\model_selection\\_validation.py\", line 895, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 669, in fit\n    return super().fit(X, y_encoded, sample_weight)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\base.py\", line 1474, in wrapper\n    return fit_method(estimator, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_stacking.py\", line 216, in fit\n    self.estimators_ = Parallel(n_jobs=self.n_jobs)(\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 67, in __call__\n    return super().__call__(iterable_with_config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1863, in __call__\n    return output if self.return_generator else list(output)\n                                                ^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\joblib\\parallel.py\", line 1792, in _get_sequential_output\n    res = func(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\utils\\parallel.py\", line 129, in __call__\n    return self.function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\sklearn\\ensemble\\_base.py\", line 36, in _fit_single_estimator\n    estimator.fit(X, y)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\sklearn.py\", line 1519, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 730, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\training.py\", line 181, in train\n    bst.update(dtrain, i, obj)\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 2050, in update\n    _check_call(\n  File \"C:\\Users\\UC\\AppData\\Roaming\\Python\\Python311\\site-packages\\xgboost\\core.py\", line 282, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [16:53:47] C:\\buildkite-agent\\builds\\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\\xgboost\\xgboost-ci-windows\\src\\common\\io.h:232: bad_malloc: Failed to allocate 5514815664 bytes.\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import scipy.io as sio\n",
    "import cv2\n",
    "from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold\n",
    "from imblearn.over_sampling import SMOTE\n",
    "from tensorflow.keras import layers, models\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.metrics import roc_auc_score, roc_curve, classification_report\n",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
    "from xgboost import XGBClassifier\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.ensemble import StackingClassifier\n",
    "import optuna\n",
    "\n",
    "# Load data\n",
    "file_path = 'C:\\\\Users\\\\UC\\\\Documents\\\\NeuMa\\\\22117124\\\\new.mat'\n",
    "new = sio.loadmat(file_path)\n",
    "ET = new['ET']\n",
    "Label_array_ET = new['label_list'].ravel()\n",
    "EEG = new['EEG']\n",
    "\n",
    "# Reshape data for SMOTE\n",
    "raw_data = ET.reshape(ET.shape[0] * ET.shape[1], -1).T\n",
    "\n",
    "# Apply SMOTE on the raw data\n",
    "smote = SMOTE(random_state=42)\n",
    "raw_data_resampled, Label_array_ET_resampled = smote.fit_resample(raw_data, Label_array_ET)\n",
    "\n",
    "# Reshape resampled data back to the original shape\n",
    "ET_resampled = raw_data_resampled.T.reshape(ET.shape[0], ET.shape[1], -1)\n",
    "\n",
    "# Create an empty list to store the images\n",
    "image_list = []\n",
    "\n",
    "# Handcrafted features\n",
    "handcrafted_features = []\n",
    "\n",
    "# Loop through each sample\n",
    "for sample_idx in range(ET_resampled.shape[2]):\n",
    "    # Extract X and Y coordinates for both eyes\n",
    "    x_left, y_left, pupil_left, x_right, y_right, pupil_right = ET_resampled[:, :, sample_idx]\n",
    "    \n",
    "    # Create a blank canvas (64x64) for the gaze plot\n",
    "    gaze_plot = np.zeros((64, 64, 3), dtype=np.uint8)  # Initialize as black image\n",
    "\n",
    "    # Scale the coordinates to match the screen size\n",
    "    scaled_x_left = (x_left * 1920 / 30).astype(int)  # 1920 / 30 ~ 64\n",
    "    scaled_y_left = (y_left * 1080 / 16.875).astype(int)  # 1080 / 16.875 ~ 64\n",
    "    scaled_x_right = (x_right * 1920 / 30).astype(int)\n",
    "    scaled_y_right = (y_right * 1080 / 16.875).astype(int)\n",
    "\n",
    "    # Set gaze points as white pixels on the canvas\n",
    "    for i in range(120):\n",
    "        if 0 <= scaled_x_left[i] < 64 and 0 <= scaled_y_left[i] < 64:\n",
    "            gaze_plot[scaled_y_left[i], scaled_x_left[i]] = [255, 255, 255]  # White color\n",
    "        if 0 <= scaled_x_right[i] < 64 and 0 <= scaled_y_right[i] < 64:\n",
    "            gaze_plot[scaled_y_right[i], scaled_x_right[i]] = [255, 255, 255]  # White color\n",
    "\n",
    "    # Append the gaze plot to the image list\n",
    "    image_list.append(gaze_plot)\n",
    "\n",
    "    # Extract handcrafted features\n",
    "    mean_left = np.mean([x_left, y_left, pupil_left])\n",
    "    std_left = np.std([x_left, y_left, pupil_left])\n",
    "    mean_right = np.mean([x_right, y_right, pupil_right])\n",
    "    std_right = np.std([x_right, y_right, pupil_right])\n",
    "    \n",
    "    # Append handcrafted features\n",
    "    handcrafted_features.append([mean_left, std_left, mean_right, std_right])\n",
    "\n",
    "# Convert the list of images to a NumPy array\n",
    "image_array = np.array(image_list)\n",
    "handcrafted_features = np.array(handcrafted_features)\n",
    "\n",
    "# Reshape images to have a single channel (grayscale)\n",
    "image_array = np.expand_dims(image_array, axis=-1)\n",
    "\n",
    "# Normalize the image data to the range [0, 1]\n",
    "image_array = image_array / 255.0\n",
    "\n",
    "# Split the data into training and test sets\n",
    "x_train_img, x_test_img, x_train_hand, x_test_hand, y_train, y_test = train_test_split(\n",
    "    image_array, handcrafted_features, Label_array_ET_resampled, test_size=0.3, random_state=42)\n",
    "\n",
    "# Define LeNet-5 for feature extraction\n",
    "lenet5 = models.Sequential([\n",
    "    layers.Conv2D(6, kernel_size=(5, 5), activation='relu', input_shape=(64, 64, 3)),\n",
    "    layers.MaxPooling2D(pool_size=(2, 2)),\n",
    "    layers.Conv2D(16, kernel_size=(5, 5), activation='relu'),\n",
    "    layers.MaxPooling2D(pool_size=(2, 2)),\n",
    "    layers.Flatten()\n",
    "])\n",
    "\n",
    "# Extract features using LeNet-5\n",
    "lenet5_features_train = lenet5.predict(x_train_img)\n",
    "lenet5_features_test = lenet5.predict(x_test_img)\n",
    "\n",
    "# Combine handcrafted features with LeNet-5 features\n",
    "x_train_combined = np.concatenate((lenet5_features_train, x_train_hand), axis=1)\n",
    "x_test_combined = np.concatenate((lenet5_features_test, x_test_hand), axis=1)\n",
    "\n",
    "# Function for Optuna optimization\n",
    "def objective(trial):\n",
    "    # Suggest hyperparameters\n",
    "    n_estimators = trial.suggest_int('n_estimators', 50, 200)\n",
    "    max_depth = trial.suggest_int('max_depth', 3, 20)\n",
    "    learning_rate = trial.suggest_float('learning_rate', 1e-4, 1e-1, log=True)\n",
    "    subsample = trial.suggest_float('subsample', 0.5, 1.0)\n",
    "    colsample_bytree = trial.suggest_float('colsample_bytree', 0.5, 1.0)\n",
    "    \n",
    "    # Define the ensemble classifier\n",
    "    estimators = [\n",
    "        ('rf', RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, random_state=42)),\n",
    "        ('gb', GradientBoostingClassifier(n_estimators=n_estimators, learning_rate=learning_rate, subsample=subsample, random_state=42)),\n",
    "        ('xgb', XGBClassifier(n_estimators=n_estimators, max_depth=max_depth, learning_rate=learning_rate, subsample=subsample, colsample_bytree=colsample_bytree, use_label_encoder=False, eval_metric='logloss', random_state=42))\n",
    "    ]\n",
    "    \n",
    "    ensemble_clf = StackingClassifier(estimators=estimators, final_estimator=RandomForestClassifier(n_estimators=100, random_state=42))\n",
    "    \n",
    "    # Cross-validation\n",
    "    skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)\n",
    "    scores = cross_val_score(ensemble_clf, x_train_combined, y_train, cv=skf, scoring='roc_auc')\n",
    "    \n",
    "    return np.mean(scores)\n",
    "\n",
    "# Optimize hyperparameters\n",
    "study = optuna.create_study(direction='maximize')\n",
    "study.optimize(objective, n_trials=5)\n",
    "\n",
    "# Get the best hyperparameters\n",
    "best_params = study.best_params\n",
    "\n",
    "# Define the ensemble classifier with best hyperparameters\n",
    "estimators = [\n",
    "    ('rf', RandomForestClassifier(n_estimators=best_params['n_estimators'], max_depth=best_params['max_depth'], random_state=42)),\n",
    "    ('gb', GradientBoostingClassifier(n_estimators=best_params['n_estimators'], learning_rate=best_params['learning_rate'], subsample=best_params['subsample'], random_state=42)),\n",
    "    ('xgb', XGBClassifier(n_estimators=best_params['n_estimators'], max_depth=best_params['max_depth'], learning_rate=best_params['learning_rate'], subsample=best_params['subsample'], colsample_bytree=best_params['colsample_bytree'], use_label_encoder=False, eval_metric='logloss', random_state=42))\n",
    "]\n",
    "\n",
    "ensemble_clf = StackingClassifier(estimators=estimators, final_estimator=RandomForestClassifier(n_estimators=100, random_state=42))\n",
    "\n",
    "# Train the ensemble classifier\n",
    "ensemble_clf.fit(x_train_combined, y_train)\n",
    "\n",
    "# Evaluate the ensemble classifier\n",
    "y_pred = ensemble_clf.predict(x_test_combined)\n",
    "y_pred_prob = ensemble_clf.predict_proba(x_test_combined)[:, 1]\n",
    "\n",
    "# Calculate and print the AUC\n",
    "auc = roc_auc_score(y_test, y_pred_prob)\n",
    "print(f\"AUC: {auc:.4f}\")\n",
    "\n",
    "# Plot AUC-ROC\n",
    "fpr, tpr, thresholds = roc_curve(y_test, y_pred_prob)\n",
    "plt.figure()\n",
    "plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {auc:.2f})')\n",
    "plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')\n",
    "plt.xlim([0.0, 1.0])\n",
    "plt.ylim([0.0, 1.05])\n",
    "plt.xlabel('False Positive Rate')\n",
    "plt.ylabel('True Positive Rate')\n",
    "plt.title('Receiver Operating Characteristic')\n",
    "plt.legend(loc='lower right')\n",
    "plt.show()\n",
    "\n",
    "# Print classification report\n",
    "print(classification_report(y_test, y_pred))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "              precision    recall  f1-score   support\n",
      "\n",
      "     Class 0       0.70      0.73      0.71      2100\n",
      "     Class 1       0.70      0.67      0.69      2024\n",
      "\n",
      "    accuracy                           0.70      4124\n",
      "   macro avg       0.70      0.70      0.70      4124\n",
      "weighted avg       0.70      0.70      0.70      4124\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import classification_report\n",
    "\n",
    "# Predict on the test set\n",
    "y_pred = ensemble_clf.predict(x_test_combined)\n",
    "\n",
    "# Print classification report\n",
    "report = classification_report(y_test, y_pred, target_names=['Class 0', 'Class 1'])\n",
    "print(report)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
